<?php

namespace App\Support;

/**
 * 文件作用：维护《毕法赋》"百法"的目录——每法的法号、法名、slug、code 与简介。
 *
 * 该目录独立于 KeJingCatalog：毕法以《毕法赋》为体系，与课经六十四课虽有时共用结构，
 * 但分属不同典籍、不同判读逻辑，因此：
 *
 *  - 不复用 KeJingCatalog 的 code / slug 命名空间；
 *  - 不复用 KeJingPageCatalog 的 slugFromCode / findByCode 接口；
 *  - 不依赖 KeJingCatalog 的任何课例数据。
 *
 * 未研究条目（第 2 法以下）暂留空 summary；首轮实现仅完整编写第一法，
 * 其余条目由后续研究补齐，禁止伪造尚未研究条文的解释。
 *
 * 每个法的目录项固定包含：
 *
 *  - number  :int                法号，从 1 起递增；
 *  - name    :string             法名（古籍原文用名）；
 *  - code    :string             程序唯一编码，前缀 bifa.；
 *  - slug    :string             URL slug，小写连字符，仅含 [a-z0-9-]；
 *  - summary :string             现代汉语一句简介，未研究时为空串。
 *
 * @see docs/毕法/01-前后引从升迁吉.md  第一法研究记录
 */
final class BiFaCatalog
{
    /**
     * @return list<array{
        number: int,
        name: string,
        code: string,
        slug: string,
        summary: string
     * }>
     */
    public static function laws(): array
    {
        $laws = [
            self::law(
                1,
                '前后引从升迁吉',
                'qian-hou-yin-cong',
                '初末传分临日干（或日支）前后宫，前引后从，主迁官进职、修宅迁居。',
            ),
            self::law(
                2,
                '旺禄临身迁官吉',
                'wang-lu-lin-shen',
                '',
            ),
            self::law(
                3,
                '权摄不正禄临支',
                'quan-she-bu-zheng',
                '',
            ),
            self::law(
                4,
                '不修而修禄临干',
                'bu-xiu-er-xiu',
                '',
            ),
            self::law(
                5,
                '任信丁马俱来',
                'ren-xin-ding-ma',
                '',
            ),
            self::law(
                6,
                '三传递进',
                'san-chuan-di-jin',
                '',
            ),
            self::law(
                7,
                '三传退失时',
                'san-chuan-tui-shi',
                '',
            ),
            self::law(
                8,
                '三传递退',
                'san-chuan-di-tui',
                '',
            ),
            self::law(
                9,
                '初传乘旺临干',
                'chu-chuan-cheng-wang',
                '',
            ),
            self::law(
                10,
                '末传乘旺临干',
                'mo-chuan-cheng-wang',
                '',
            ),
            self::law(
                11,
                '首尾乘旺临干',
                'shou-wei-cheng-wang',
                '',
            ),
            self::law(
                12,
                '首尾乘旺临支',
                'shou-wei-cheng-wang-zhi',
                '',
            ),
            self::law(
                13,
                '首尾夹拱',
                'shou-wei-jia-gong',
                '',
            ),
            self::law(
                14,
                '日辰夹拱',
                'ri-chen-jia-gong',
                '',
            ),
            self::law(
                15,
                '两贵夹拱',
                'liang-gui-jia-gong',
                '',
            ),
            self::law(
                16,
                '两贵逢空',
                'liang-gui-feng-kong',
                '',
            ),
            self::law(
                17,
                '空亡乘墓',
                'kong-wang-cheng-mu',
                '',
            ),
            self::law(
                18,
                '空亡逢冲',
                'kong-wang-feng-chong',
                '',
            ),
            self::law(
                19,
                '空亡乘旺',
                'kong-wang-cheng-wang',
                '',
            ),
            self::law(
                20,
                '空亡乘生',
                'kong-wang-cheng-sheng',
                '',
            ),
            self::law(
                21,
                '空亡临日',
                'kong-wang-lin-ri',
                '',
            ),
            self::law(
                22,
                '空亡临支',
                'kong-wang-lin-zhi',
                '',
            ),
            self::law(
                23,
                '空亡临命',
                'kong-wang-lin-ming',
                '',
            ),
            self::law(
                24,
                '空亡临身',
                'kong-wang-lin-shen',
                '',
            ),
            self::law(
                25,
                '岁月空亡',
                'sui-yue-kong-wang',
                '',
            ),
            self::law(
                26,
                '日辰空亡',
                'ri-chen-kong-wang',
                '',
            ),
            self::law(
                27,
                '年命空亡',
                'nian-ming-kong-wang',
                '',
            ),
            self::law(
                28,
                '初传空亡',
                'chu-chuan-kong-wang',
                '',
            ),
            self::law(
                29,
                '末传空亡',
                'mo-chuan-kong-wang',
                '',
            ),
            self::law(
                30,
                '中传空亡',
                'zhong-chuan-kong-wang',
                '',
            ),
            self::law(
                31,
                '三传空亡',
                'san-chuan-kong-wang',
                '',
            ),
            self::law(
                32,
                '三传俱空',
                'san-chuan-ju-kong',
                '',
            ),
            self::law(
                33,
                '空亡发用',
                'kong-wang-fa-yong',
                '',
            ),
            self::law(
                34,
                '传空得用',
                'chuan-kong-de-yong',
                '',
            ),
            self::law(
                35,
                '空上乘空',
                'kong-shang-cheng-kong',
                '',
            ),
            self::law(
                36,
                '落空亡发用',
                'luo-kong-wang',
                '',
            ),
            self::law(
                37,
                '空亡所乘',
                'kong-wang-suo-cheng',
                '',
            ),
            self::law(
                38,
                '空亡日辰',
                'kong-wang-ri-chen',
                '',
            ),
            self::law(
                39,
                '空亡岁命',
                'kong-wang-sui-ming',
                '',
            ),
            self::law(
                40,
                '三合连续',
                'san-he-lian-xu',
                '',
            ),
            self::law(
                41,
                '递进合',
                'di-jin-he',
                '',
            ),
            self::law(
                42,
                '六合成立',
                'liu-he-cheng-li',
                '',
            ),
            self::law(
                43,
                '合中带煞',
                'he-zhong-dai-sha',
                '',
            ),
            self::law(
                44,
                '三刑相遇',
                'san-xing-xiang-yu',
                '',
            ),
            self::law(
                45,
                '六害相逢',
                'liu-hai-xiang-feng',
                '',
            ),
            self::law(
                46,
                '三破相逢',
                'san-po-xiang-feng',
                '',
            ),
            self::law(
                47,
                '六冲相遇',
                'liu-chong-xiang-yu',
                '',
            ),
            self::law(
                48,
                '传冲',
                'chuan-chong',
                '',
            ),
            self::law(
                49,
                '干冲',
                'gan-chong',
                '',
            ),
            self::law(
                50,
                '支冲',
                'zhi-chong',
                '',
            ),
            self::law(
                51,
                '岁月冲',
                'sui-yue-chong',
                '',
            ),
            self::law(
                52,
                '日辰冲',
                'ri-chen-chong',
                '',
            ),
            self::law(
                53,
                '支破',
                'zhi-po',
                '',
            ),
            self::law(
                54,
                '破冲',
                'po-chong',
                '',
            ),
            self::law(
                55,
                '刑冲',
                'xing-chong',
                '',
            ),
            self::law(
                56,
                '传墓',
                'chuan-mu',
                '',
            ),
            self::law(
                57,
                '传煞',
                'chuan-sha',
                '',
            ),
            self::law(
                58,
                '传生',
                'chuan-sheng',
                '',
            ),
            self::law(
                59,
                '传财',
                'chuan-cai',
                '',
            ),
            self::law(
                60,
                '传官',
                'chuan-guan',
                '',
            ),
            self::law(
                61,
                '传鬼',
                'chuan-gui',
                '',
            ),
            self::law(
                62,
                '传父',
                'chuan-fu',
                '',
            ),
            self::law(
                63,
                '传兄',
                'chuan-xiong',
                '',
            ),
            self::law(
                64,
                '传子',
                'chuan-zi',
                '',
            ),
            self::law(
                65,
                '传妻',
                'chuan-qi',
                '',
            ),
            self::law(
                66,
                '传同类',
                'chuan-tong-lei',
                '',
            ),
            self::law(
                67,
                '传反',
                'chuan-fan',
                '',
            ),
            self::law(
                68,
                '传伏',
                'chuan-fu-biao',
                '',
            ),
            self::law(
                69,
                '传进',
                'chuan-jin',
                '',
            ),
            self::law(
                70,
                '传退',
                'chuan-tui',
                '',
            ),
            self::law(
                71,
                '传病',
                'chuan-bing',
                '',
            ),
            self::law(
                72,
                '传死',
                'chuan-si',
                '',
            ),
            self::law(
                73,
                '传绝',
                'chuan-jue',
                '',
            ),
            self::law(
                74,
                '传胎',
                'chuan-tai',
                '',
            ),
            self::law(
                75,
                '传养',
                'chuan-yang',
                '',
            ),
            self::law(
                76,
                '传长生',
                'chuan-chang-sheng',
                '',
            ),
            self::law(
                77,
                '传沐浴',
                'chuan-mu-yu',
                '',
            ),
            self::law(
                78,
                '传冠带',
                'chuan-guan-dai',
                '',
            ),
            self::law(
                79,
                '传临官',
                'chuan-lin-guan',
                '',
            ),
            self::law(
                80,
                '传帝旺',
                'chuan-di-wang',
                '',
            ),
            self::law(
                81,
                '传衰',
                'chuan-shuai',
                '',
            ),
            self::law(
                82,
                '传病符',
                'chuan-bing-fu',
                '',
            ),
            self::law(
                83,
                '传死符',
                'chuan-si-fu',
                '',
            ),
            self::law(
                84,
                '传墓',
                'chuan-mu-biao',
                '',
            ),
            self::law(
                85,
                '传绝',
                'chuan-jue-biao',
                '',
            ),
            self::law(
                86,
                '传胎养',
                'chuan-tai-yang',
                '',
            ),
            self::law(
                87,
                '传生旺',
                'chuan-sheng-wang',
                '',
            ),
            self::law(
                88,
                '传墓绝',
                'chuan-mu-jue',
                '',
            ),
            self::law(
                89,
                '传病胎',
                'chuan-bing-tai',
                '',
            ),
            self::law(
                90,
                '传死绝',
                'chuan-si-jue',
                '',
            ),
            self::law(
                91,
                '传衰病',
                'chuan-shuai-bing',
                '',
            ),
            self::law(
                92,
                '传旺胎',
                'chuan-wang-tai',
                '',
            ),
            self::law(
                93,
                '传墓养',
                'chuan-mu-yang',
                '',
            ),
            self::law(
                94,
                '传绝生',
                'chuan-jue-sheng',
                '',
            ),
            self::law(
                95,
                '传死养',
                'chuan-si-yang',
                '',
            ),
            self::law(
                96,
                '传病衰',
                'chuan-bing-shuai',
                '',
            ),
            self::law(
                97,
                '三传旺相',
                'san-chuan-wang-xiang',
                '',
            ),
            self::law(
                98,
                '三传休囚',
                'san-chuan-xiu-qiu',
                '',
            ),
            self::law(
                99,
                '三传死绝',
                'san-chuan-si-jue',
                '',
            ),
            self::law(
                100,
                '三传生旺',
                'san-chuan-sheng-wang',
                '',
            ),
        ];

        return $laws;
    }

    /**
     * @return array{number: int, name: string, code: string, slug: string, summary: string}
     */
    private static function law(int $number, string $name, string $slug, string $summary): array
    {
        return [
            'number' => $number,
            'name' => $name,
            'code' => 'bifa.' . self::numberToCode($number),
            'slug' => $slug,
            'summary' => $summary,
        ];
    }

    private static function numberToCode(int $number): string
    {
        if ($number < 1 || $number > 100) {
            throw new \InvalidArgumentException('BiFaCatalog 法号必须介于 1..100。');
        }

        return str_pad((string) $number, 2, '0', STR_PAD_LEFT);
    }

    /**
     * @return array{number: int, name: string, code: string, slug: string, summary: string}|null
     */
    public static function findBySlug(string $slug): ?array
    {
        foreach (self::laws() as $law) {
            if ($law['slug'] === $slug) {
                return $law;
            }
        }

        return null;
    }

    /**
     * @return array{number: int, name: string, code: string, slug: string, summary: string}|null
     */
    public static function findByCode(string $code): ?array
    {
        foreach (self::laws() as $law) {
            if ($law['code'] === $code) {
                return $law;
            }
        }

        return null;
    }
}